

version: '3'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/assignment
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=assignment.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:80"
      
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
