
FROM python:3.10

WORKDIR /assignment

COPY . /assignment

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

ENV DJANGO_SETTINGS_MODULE=assignment.settings

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "assignment.wsgi:application"]
